### PR TITLE
Fix webpkgserver so that it can read dummy OCSP in the cert cache. 

### LINKED ISSUE #67: Fix webpkgserver so it doesn't error out due to dummy OCSP response
When serving self-signed certs using locahost:8080/webpkg/cert/xxxx (where xxx = cert digest), the webpkgserver gives out an error while reading the dummy OCSP response in the cert cache:

* asn1: structure error: tags don't match (16 vs {class:1 tag:4 length:117 isCompound:true}) {optional:false exp
licit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:fal
se} responseASN1 @2

### PR DESCRIPTION
**Pull request by banaag**
Fix webpkgserver so that it can read dummy OCSP in the cert cache and render it properly from /webpkg/cert.
Fixes #67

### CODE REVIEW

File: certchain/ocsp_response.go [hunk 1]
```diff
@@ -53,6 +53,9 @@ var DummyOCSPResponse *OCSPResponse = &OCSPResponse{
 func ParseOCSPResponse(bytes []byte) (*OCSPResponse, error) {
 	resp, err := ocsp.ParseResponse(bytes, nil)
 	if err != nil {
+		if string(bytes) == "dummy-ocsp" {
```
Comment (twifkak) [inline certchain/ocsp_response.go:56]: Can you say `== DummyOCSPResponse.Raw` instead?

File: certchain/ocsp_response.go [hunk 2]
```diff
@@ -53,6 +53,9 @@ var DummyOCSPResponse *OCSPResponse = &OCSPResponse{
...
+			return DummyOCSPResponse, nil
```
Comment (twifkak) [inline certchain/ocsp_response.go:57]: Add a comment to explain this is necessary to serve a(n invalid) cert-chain+cbor in AllowTestCert mode.

**Review by twifkak — CHANGES_REQUESTED** [review]

File: certchain/ocsp_response.go (hunk 1 above)
Comment (banaag) [reply certchain/ocsp_response.go]: Changed but it has to be cast to string because I can't compare byte slices, it only allows for nil comparison.

File: certchain/ocsp_response.go (hunk 2 above)
Comment (banaag) [reply certchain/ocsp_response.go:59]: Done.

File: certchain/ocsp_response.go (hunk 1 above)
Comment (twifkak) [reply certchain/ocsp_response.go]: Works for me. IIRC, casting bytes to string is cheap (reuses underlying buffer).

**Review by twifkak — APPROVED** [review]
